<?php
/**
 * Plugin Name: Custom Code Manager
 * Plugin URI: https://www.spacexchimp.com/plugins/custom-code-manager.html
 * Description: Easily and safely add your custom PHP/HTML/CSS/JavaScript code to your WordPress website, directly out of the WordPress Admin Area, without the need to have an external editor.
 * Author: Space X-Chimp
 * Author URI: https://www.spacexchimp.com
 * Version: 1.1
 * License: GPL3
 * Text Domain: custom-code-manager
 * Domain Path: /languages/
 *
 * Copyright 2019 Space X-Chimp ( website : https://www.spacexchimp.com )
 *
 * All PHP code, and PDF/POT/PO/MO files is released under the GNU General Public License, version 3.
 * All HTML/CSS/JAVASCRIPT code, and PNG files is released under the restrictive proprietary license.
 *
 * ███████╗██████╗  █████╗  ██████╗███████╗    ██╗  ██╗      ██████╗██╗  ██╗██╗███╗   ███╗██████╗
 * ██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝    ╚██╗██╔╝     ██╔════╝██║  ██║██║████╗ ████║██╔══██╗
 * ███████╗██████╔╝███████║██║     █████╗       ╚███╔╝█████╗██║     ███████║██║██╔████╔██║██████╔╝
 * ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝       ██╔██╗╚════╝██║     ██╔══██║██║██║╚██╔╝██║██╔═══╝
 * ███████║██║     ██║  ██║╚██████╗███████╗    ██╔╝ ██╗     ╚██████╗██║  ██║██║██║ ╚═╝ ██║██║
 * ╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝    ╚═╝  ╚═╝      ╚═════╝╚═╝  ╚═╝╚═╝╚═╝     ╚═╝╚═╝
 *
 */


/**
 * Prevent Direct Access
 */
defined( 'ABSPATH' ) or die( "Restricted access!" );

/**
 * Define global constants
 */
$plugin_data = get_file_data( __FILE__,
                              array(
                                     'name'    => 'Plugin Name',
                                     'version' => 'Version',
                                     'text'    => 'Text Domain'
                                   )
                            );
function spacexchimp_p020_define_constants( $constant_name, $value ) {
    $constant_name = 'SPACEXCHIMP_P020_' . $constant_name;
    if ( ! defined( $constant_name ) )
        define( $constant_name, $value );
}
spacexchimp_p020_define_constants( 'FILE', __FILE__ );
spacexchimp_p020_define_constants( 'DIR', dirname( plugin_basename( __FILE__ ) ) );
spacexchimp_p020_define_constants( 'BASE', plugin_basename( __FILE__ ) );
spacexchimp_p020_define_constants( 'URL', plugin_dir_url( __FILE__ ) );
spacexchimp_p020_define_constants( 'PATH', plugin_dir_path( __FILE__ ) );
spacexchimp_p020_define_constants( 'SLUG', dirname( plugin_basename( __FILE__ ) ) );
spacexchimp_p020_define_constants( 'NAME', $plugin_data['name'] );
spacexchimp_p020_define_constants( 'VERSION', $plugin_data['version'] );
spacexchimp_p020_define_constants( 'TEXT', $plugin_data['text'] );
spacexchimp_p020_define_constants( 'PREFIX', 'spacexchimp_p020' );
spacexchimp_p020_define_constants( 'SETTINGS', 'spacexchimp_p020' );

/**
 * A useful function that returns an array with the contents of plugin constants
 */
function spacexchimp_p020_plugin() {
    $array = array(
        'file'     => SPACEXCHIMP_P020_FILE,
        'dir'      => SPACEXCHIMP_P020_DIR,
        'base'     => SPACEXCHIMP_P020_BASE,
        'url'      => SPACEXCHIMP_P020_URL,
        'path'     => SPACEXCHIMP_P020_PATH,
        'slug'     => SPACEXCHIMP_P020_SLUG,
        'name'     => SPACEXCHIMP_P020_NAME,
        'version'  => SPACEXCHIMP_P020_VERSION,
        'text'     => SPACEXCHIMP_P020_TEXT,
        'prefix'   => SPACEXCHIMP_P020_PREFIX,
        'settings' => SPACEXCHIMP_P020_SETTINGS
    );
    return $array;
}

/**
 * Put value of plugin constants into an array for easier access
 */
$plugin_combo = spacexchimp_p020_plugin();

/**
 * Register the 'Code' menu item in the Admin Menu
 */
function spacexchimp_p020_register_admin_menu() {

    // Put value of plugin constants into an array for easier access
    $plugin = spacexchimp_p020_plugin();

    // Return if the 'Code' menu item is already exists
    if ( !empty ( $GLOBALS['admin_page_hooks']['code'] ) ) {
        return;
    }

    $page_title = __( 'Code', $plugin['text'] );
    $menu_title = __( 'Code', $plugin['text'] );
    $capability = 'manage_options';
    $menu_slug  = 'code';
    $function   = null;
    $icon_url   = 'dashicons-admin-generic';
    $position   = 66;

    add_menu_page( $page_title, $menu_title, $capability, $menu_slug, $function, $icon_url, $position );
}
add_action( 'admin_menu', $plugin_combo['prefix'] . '_register_admin_menu' );

/**
 * Remove the 'Code' sub menu item in the brand menu item
 */
function spacexchimp_p020_remove_submenu_item() {
    remove_submenu_page( 'code', 'code' );
}
add_action( 'admin_menu', $plugin_combo['prefix'] . '_remove_submenu_item', 999 );

/**
 * Print direct link to the plugin administration page
 *
 * Fetches array of links generated by WordPress Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the plugin admin page
 */
function spacexchimp_p020_settings_link( $links ) {

    // Put value of plugin constants into an array for easier access
    $plugin = spacexchimp_p020_plugin();

    // Declare variables
    $text_settings = __( 'Settings', $plugin['text'] );
    $url_settings = admin_url( 'admin.php?page=code/html' );
    $link_settings = '<a href="' . $url_settings . '">' . $text_settings . '</a>';

    array_unshift( $links, $link_settings );

    return $links;
}
add_filter( 'plugin_action_links_' . $plugin_combo['base'], $plugin_combo['prefix'] . '_settings_link' );

/**
 * Print additional links to the plugin meta row
 */
function spacexchimp_p020_plugin_row_meta( $links, $file ) {

    // Put value of plugin constants into an array for easier access
    $plugin = spacexchimp_p020_plugin();

    if ( strpos( $file, $plugin['slug'] . '.php' ) !== false ) {

        // Declare variables
        $url_donate = "https://www.spacexchimp.com/donate.html";
        $text_donate = __( 'Donate', $plugin['text'] );
        $link_donate = '<a href="' . $url_donate . '" target="_blank"><span class="dashicons dashicons-heart"></span> ' . $text_donate . '</a>';

        $new_links = array(
                           'donate' => $link_donate
                           );

        $links = array_merge( $links, $new_links );
    }

    return $links;
}
add_filter( 'plugin_row_meta', $plugin_combo['prefix'] . '_plugin_row_meta', 10, 2 );

/**
 * Load the plugin modules
 */
require_once( $plugin_combo['path'] . 'html/main.php' );
require_once( $plugin_combo['path'] . 'js/main.php' );
require_once( $plugin_combo['path'] . 'php/main.php' );
require_once( $plugin_combo['path'] . 'css/main.php' );
